# Generated by Django 3.2 on 2022-11-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
